name: chronicle
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.5
  flutter_acrylic: ^1.1.0
  hid_listener:
    path: vendor/hid_listener
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  timeline_list: ^0.0.3 # https://pub.dev/packages/timeline_list
  screen_capturer: ^0.1.7
  path_provider: ^2.0.15
  sqflite_common_ffi: ^2.3.0+2
  path: ^1.8.3
  image: ^4.0.17
  intl: ^0.18.1
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
